<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Login</title>
<link rel="stylesheet" type="text/css" href="./colors/color2/view.css" media="all">
<script type="text/javascript" src="js/view.js"></script>
<script type="text/javascript" src="js/calendar.js"></script>
</head>
<body id="main_body" >
	
	
	<?php
		if(isset($_POST['submit']))
		{
			require('DbDataAdapter.php');
			
			$userDa = new UsersTableDataAdapter();
			
			$userId = $userDa->AuthenticateUser($_POST['element_1'], $_POST['element_2']);
			if($userId == -1)
			{
				echo("Invalid login info.");
			}
			else
			{
				// User is authenticated
				$groupsDa = new GroupsTableAdapter();
				$groupsDa->AddGroupAffiliation($userId, $_GET['groupId']);
				
				die("You have successfully joined the group.  You may now return to the app and participate.");
			}
		}
	?>
	
	<img id="top" src="images/top.png" alt="">
	<div id="form_container">
	
		<h1><a>Login</a></h1>
		<form id="form_352443" class="appnitro"  method="post" action="AcceptInvitation.php?groupId=<?php echo($_GET['groupId']); ?>">
					<div class="form_description">
			<h2>Login</h2>
			<p>Login to Lunch on Me to accept group invitation.</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Username </label>
		<div>
			<input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Password </label>
		<div>
			<input id="element_2" name="element_2" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="352443" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="images/bottom.png" alt="">
	</body>
</html>